# Display message to the screen
print("Welcome to COM411!")
print("In week 1 we will learn...")
print()
print("...How to use Git and Github")
print("...How to output to the screen")
print("...How to get user input")
print()
print("i hope you are enjoying the lesson thus far!")
print()
# Display escape characters
print("\n Displays a new line")
print("\t Displays a tab space")
print("\\ Displays a back slash")
print("\" Displays a double quote")
print("\' Displays a single quote")
print()
print("\t\"I am programming!\"")
